# Generated by Django 5.2.17 on 2026-08-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
